version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - WELL_KNOWN_URL=${WELL_KNOWN_URL}
      - PORT=${PORT}
      - HOST=${HOST}
      - REDIRECT_HOST=${REDIRECT_HOST}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
      - ROOT_CA=${ROOT_CA}
    networks:
      - clientnet
networks:
  clientnet:
    external: true
    name: authorization_system

