version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18888:18888
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - ISSUER_URL=${ISSUER_URL}
      - PORT=${PORT}
      - HOST=${HOST}
      - REDIRECT_HOST=${REDIRECT_HOST}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
      - ROOT_CA=${ROOT_CA}
      - PKCE_ENABLED=${PKCE_ENABLED}
networks:
  test:
    external: true
    name: authorization_system

