version: '3'

services:
  oauth_client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - default
networks:
  default:
    name: pyron-authorizer_default

