version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - WELL_KNOWN_URL=${WELL_KNOWN_URL}
      - PORT=${PORT}
      - HOST=${HOST}
      - REDIRECT_HOST=${REDIRECT_HOST}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
      - ROOT_CA=${ROOT_CA}
      - USE_PYRON=${USE_PYRON}
      - X_SSL_CERT_HASH=${X_SSL_CERT_HASH}
      - RESOURCE_URL=${RESOURCE_URL}
    networks:
      - default
networks:
  default:
    name: pyron-authorizer_default

