version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - ISSUER_URL=${ISSUER_URL}
      - AUTHORIZATION_ENDPOINT=${AUTHORIZATION_ENDPOINT}
      - MTLS_ENDPOINT_ALIASES_TOKEN_ENDPOINT=${MTLS_ENDPOINT_ALIASES_TOKEN_ENDPOINT}
      - PORT=${PORT}
      - HOST=${HOST}
      - REDIRECT_HOST=${REDIRECT_HOST}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
      - ROOT_CA=${ROOT_CA}
      - PKCE_ENABLED=${PKCE_ENABLED}
    networks:
      - clientnet
networks:
  clientnet:
    external: true
    name: authorization_system

